### ISSUE TITLE
Does the bot still work? Or does it not work anymore because instagram the new API?

### ISSUE THREAD

**Issue by alswind** [Garlicvideos/reddits-nightmare#10]

**Comment by Axiver** [comment]
I will test the bot tomorrow and get back to you.

**Comment by Axiver** [comment]
I can confirm that the bot is still in working condition.
I recommend using the current version in the develop branch, which you can download [here](https://github.com/Garlicvideos/reddits-nightmare/archive/develop.zip)
Have fun!
