### ISSUE TITLE
Amount of posts per day or a time zone when the bot posts

### ISSUE THREAD

**Issue by RemmelHemmel** [Garlicvideos/reddits-nightmare#11]
**First @Garlicvideos I love your Project**

But I want that the bot posts only one or two pictures a day.
I trieded to use the function: "_setInterval(chooseInstaPhoto, 1.5e+6)_;"  and used a time of 12h --> 4.32e+7 but since I changed the line the bot wasn't posting at all.

Do you know what the Problem is or how i coud fix my Problem (maybe that isn't a good way and you know a better way to solve the Problem)

LG

**Comment by Axiver** [comment]
That's interesting. 4.32e+7 should work as a delay for setInterval.

I have a few questions:
Even if the bot does not upload anything to Instagram, does it continue to scrape reddit? (You would know by the bot telling you that it is downloading new posts in the console)
Did anything related to posting on Instagram show up on the console? Perhaps some kind of error?
If the bot is set back to regular intervals, does it upload images successfully?

You could temporarily use the [cron npm module](https://www.npmjs.com/package/cron).

To use the package, install it and replace 

`setInterval(chooseInstaPhoto, 1.5e+6);` with

`var CronJob = require('cron').CronJob;
var job = new CronJob('0 0 */12 * * *', chooseInstaPhoto(), null, true, 'America/Los_Angeles');
job.start();`

Don't forget to replace `America/Los_Angeles` with your timezone :).

In the meantime, I will look further into this and test on my end.

**Comment by RemmelHemmel** [comment]
Yes it continues with scraping from reddit but the Idea with Cron is perfect Thanks!
