### ISSUE TITLE
Downloads Fine, No errors, but never posts

### ISSUE THREAD

**Issue by Motzumoto** [Garlicvideos/reddits-nightmare#12]
Does it post after a set time or do i have to do that manually?

**Comment by Axiver** [comment]
Hi, my apologies for the late reply.

It is meant to be uploading posts every 25 Minutes.

Could you paste a copy of the console here?
Have you modified any of the code in beepboop.js?

I will look into this issue on my end.

**Comment by Axiver** [comment]
Hi. I have checked on this, and it seems like the bot is working perfectly fine on my end.

I would need a response to the above questions to help resolve this issue.

Please try to get back to me as soon as possible :).

**Comment by Axiver** [comment]
Due to inactivity, I will be closing this issue. Feel free to re-open it if the problem persists.
