### ISSUE TITLE
Issue running installer 

### ISSUE THREAD

**Issue by LeoRino** [Garlicvideos/reddits-nightmare#13]
Hello, 
I am new to all of this so sorry if my questions seem really obvious.
When running the installer (after running npm i) I get an error message telling me that there is something wrong. I attached a screenshot I'd appreciate if someone could help me solve this. The file in question is in the directory so I don't understand why the installer can't find it. I tried this on both mac and windows, and got the same error.
Thanks, Leo
![Capture](https://user-images.githubusercontent.com/73493577/97212278-73451900-17c0-11eb-8aaf-7cc06cea1813.PNG)

**Comment by justmadethis** [comment]
Same problem, just made this account to ask for help.

**Comment by RemmelHemmel** [comment]
Do something good for mankind and just use Linux and it will work ;)

You can just use a subsystem WLS 2 on Windows is much better suited for that.

**Comment by Axiver** [comment]
@LeoRino may I know what your file structure is like?

My apologies for the late reply, my computer is dead at the moment and I’m working on getting a new one.

**Comment by Axiver** [comment]
As this thread has been inactive for well over a month now, I will be closing it. Feel free to re-open if this is still an issue you face.
