### ISSUE TITLE
A stupid question about the bot

### ISSUE THREAD

**Issue by molotovah** [Garlicvideos/reddits-nightmare#20]
Hello,

I managed to get the script working but after the configuration I can't launch it again without doing the customization again.

Is there a way to launch the bot with the previous config ?

I want to be able to use cron @reboot 

Thanks

**Comment by Axiver** [comment]
Hi, do you mean that after launch, the bot walks you through the entire setup process again?
Nothing is saved, not even the list of subreddits you specified previously?

Can I confirm that your file structure looks like the following after completing initial setup?

![image](https://user-images.githubusercontent.com/33229805/173498782-84351f96-6a6c-471f-afdf-210c3c41c12f.png)

Especially the files in the /config/ directory.

**Comment by Axiver** [comment]
As this thread has been inactive for well over a month now, I will be closing it. Feel free to re-open if this is still an issue you face.
