### ISSUE TITLE
custom caption issue

### ISSUE THREAD

**Issue by msumeet** [Garlicvideos/reddits-nightmare#21]
I've added hashtags in the custom caption file in the below format
<#hastag1 #hastag2 #hastag3>

But when the post gets published, it writes undefined.

How do you think I could fix this?

**Comment by Axiver** [comment]
Hi there, this issue should be fixed in the [latest release](https://github.com/Garlicvideos/reddits-nightmare/releases/latest).

If you still encounter the problem, feel free to re-open this issue!

**Comment by msumeet** [comment]
cool, thanks :)
