### ISSUE TITLE
Error when attempting to run the script.

### ISSUE THREAD

**Issue by sdcombo12** [Garlicvideos/reddits-nightmare#22]
When I try to run the automatic setup I receive this error, what am I doing wrong?

![Screenshot 2022-07-29 161747](https://user-images.githubusercontent.com/82682662/181779934-99b22ea8-436a-40d8-b67e-61c68de570c6.png)

**Comment by Axiver** [comment]
You're getting that error because required packages are missing.

You need to run `npm i` before running `node beepboop.js`.

`npm i` installs the required packages. Do let me know how it goes!

**Comment by Axiver** [comment]
As this thread has been inactive for well over a month now, I will be closing it. Feel free to re-open if this is still an issue you face.
