### ISSUE TITLE
Found a potentially NSFW post (Will require manual approval):

### ISSUE THREAD

**Issue by turpez** [Garlicvideos/reddits-nightmare#29]
it tells me how I can approve it manually ?      : Found a potentially NSFW post (Will require manual approval):

**Comment by Axiver** [comment]
Hi, to approve the post, simply drag it from the `/nsfw` folder to the `/approved` folder manually

**Comment by Axiver** [comment]
If you're still unsure on how to resolve this issue, feel free to re-open the issue
