### ISSUE TITLE
Missing important files

### ISSUE THREAD

**Issue by kevinscholten** [Garlicvideos/reddits-nightmare#5]
Hello,

You have some important files in the .gitignore file which are necessary for the bot to function.

**Comment by Axiver** [comment]
They are generated by the bot automatically to suit your needs. Simply install the node modules required by the bot, run it in auto setup and answer the questions it asks.

For more information, take a look at the [ReadMe file](https://github.com/Garlicvideos/reddits-nightmare/blob/master/README.md)

If you've followed the above steps and the bot still doesn't work, please paste the crash log, or any error messages that have come up and I'll solve it with you.

**Comment by kevinscholten** [comment]
`\Documents\GitHub\reddits-nightmare\bot\beepboop.js:191
                        let ocrtext = await ocr(myImage, worker);
                        ^^^

SyntaxError: Lexical declaration cannot appear in a single-statement context
[90m    at Module._compile (internal/modules/cjs/loader.js:881:18)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:798:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:711:12)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m`

This is what it says after installing the needed node modules and running node beepboop.js.

**Comment by Axiver** [comment]
Looks like something broke in the latest release. Download [this version instead](https://github.com/Garlicvideos/reddits-nightmare/releases/tag/1.2.0). Its a version behind, but all of the major features are present, including OCR.

I'll update you with a new release when I fix it. For now, try using v1.2.0 and tell me how it goes!

**Comment by Axiver** [comment]
Scratch that, I just fixed the bug.
Download the latest release [here](https://github.com/Garlicvideos/reddits-nightmare/releases/tag/1.2.2).
