### ISSUE TITLE
Human verification received from Instagram! Solving challenge...

### ISSUE THREAD

**Issue by crocogab** [Garlicvideos/reddits-nightmare#7]
Hello im new and very bad in coding can u explain me what i have to do ?
{ step_name: 'verify_code',
  step_data:
   { security_code: 'None',
     sms_resend_delay: 60,
     phone_number_preview: '6 30',
     resend_delay: 60,
     contact_point: '6 30',
     form_type: 'phone_number',
     phone_number_formatted: '+33 * ** ** ** **',
     phone_number: '+33 * ** ** ** **' },
  user_id: 25521456322,
  nonce_code: 'JVhDTBkdHu',
  status: 'ok' }

Ty in advance

**Comment by Axiver** [comment]
Login to Instagram yourself on [Instagram's site](https://www.instagram.com/)

Afterwards, you will be greeted with a "Human Verification Challenge".
Looking at the error message from the bot, the challenge type is a SMS Challenge.

After the challenge has been solved by yourself on Instagram, re-run the bot and it should work.
I am working on getting the bot to solve the challenges by itself, and that feature will come out in a future update :)

**Comment by crocogab** [comment]
> Connectez-vous à Instagram vous-même sur [le site Instagram](https://www.instagram.com/)
> 
> Ensuite, vous serez accueillis avec un "défi de vérification humaine".
> En regardant le message d'erreur du bot, le type de défi est un défi SMS.
> 
> Une fois le défi résolu par vous-même sur Instagram, relancez le bot et cela devrait fonctionner.
> Je travaille à obtenir le bot pour résoudre les défis par lui-même, et cette fonctionnalité sortira dans une future mise à jour :)

ty very much
