### ISSUE TITLE
Will not progress after it has downloaded Images

### ISSUE THREAD

**Issue by JustenG** [Garlicvideos/reddits-nightmare#8]
I'm not sure if it is getting stuck downloading the images, or if it has completed the download.

But with options.limit set to 4 and in accounts, "top" is equal to 3, I do not get passed the download phase. Even though the program successfully downloads 2 photos.

Edit: After setting options.limit to 15, I'm stuck on downloading the 10th image
It's always getting stuck, just at a value lower than the set snoop amount
Another thing to note, this is after we have successfully signed into Instagram

**Comment by Axiver** [comment]
Just so I’m on the same page as you; What do you mean by “stuck”?

The bot does not re-download any posts that it has already previously downloaded. This means that the bot may have downloaded only 10 images on your second boot as the other 5 may have already been downloaded during your previous boots.

The bot will only tell you that it has completed downloading specific posts, and not the entire bunch it was targeting. Chances are, the bot isn’t stuck, it’s just done :p

Also, the bot will only upload images to Instagram 25 minutes after boot and every subsequent 25 minutes afterwards unless that value is changed.

As it is waiting for that timer to countdown, the bot will remain silent while watching reddit for posts meeting the criteria specified.

So yea, unless the bots behaviour is not like what I’ve listed above, it shouldn’t have a problem.

But if there is, do reply with a copy of your consoles output.

**Comment by JustenG** [comment]
Okay, I set the time to 2m for debugging

Looks like it is actually working! I might add some logs to make it a little more clear.

I however did get an aspect ratio fail when trying to upload an image.

If I get time I might write up a fallback for if this does happen, so that the bot marks it as used and tries the next one on the list

**Comment by Axiver** [comment]
Since the bot is behaving as expected, this issue will be closed. All pull requests are welcomed.
