### ISSUE TITLE
Downloading broken files

### ISSUE THREAD

**Issue by JustenG** [Garlicvideos/reddits-nightmare#9]
The bot will download a collection of images, most being okay.
I however have notice that it has downloaded an empty file with no file extension.

Trying to delete this file is not possible, unless opening the command prompt and force deleting the approved folder.

I have attached images of the resulting empty folder.

This is the file and its error message when trying to delete it for windows gui
![image](https://user-images.githubusercontent.com/13634710/73891754-0784ee00-48c9-11ea-989b-91d0a9e5631a.png)

This is the bot when trying to upload the file
![image](https://user-images.githubusercontent.com/13634710/73891723-f4721e00-48c8-11ea-9fa4-8e43e3f293b4.png)

After deleting this file successfully and running the bot again, the file is re-downloaded, and still broken, leading me to believe that it is in fact downloading an empty file

EDIT: The img URL that keeps braking is; 
https://i.redd.it/hglmdbr5cie41.jpg

**Comment by JustenG** [comment]
Resolved!

The file that was being downloaded has a windows forbidden character in the file name.
A colon was present.

Implementing a forbidden character remover will solve this issue

**Comment by Axiver** [comment]
I will push a fix for this as soon as I can.

**Comment by Axiver** [comment]
This issue, along with a ratio check fallback has now been fixed and added respectively in the latest push at the develop branch.
[Develop Branch](https://github.com/Garlicvideos/reddits-nightmare/tree/develop)
